### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by cooperspencer** [rday/zabbix#6]
Hi,

when I try to log in with your api I get following error message:
`x509: certificate signed by unknown authority`

The problem is that my colleagues used a self signed certificate.
Do you have any ideas how to solve this?

**Comment by rday** [comment]
Hi Andreas,

Is that error originating from the server? It’s been awhile since I’ve looked at this library, so I am a bit rusty.

Is there a config on your server where you could mark your self signed CA as a trusted certificate?

**Comment by cooperspencer** [comment]
No I can't...
From what I've seen so far it could work if the login process would work if I could skip the SSL verification.

`tls.Config{InsecureSkipVerify: true}`

**Comment by cooperspencer** [comment]
So far I've managed to fix it to suit my needs
